-- Raporlar (reports) ve HST Raporu Detayları (report_hst_content) tablolarındaki varsayılan değeri olmayan alanların düzeltilmesi
-- Tarih: 2026-09-20

ALTER TABLE `reports`
    MODIFY COLUMN `report_number` VARCHAR(50) NULL DEFAULT '',
    MODIFY COLUMN `report_type` VARCHAR(255) NULL DEFAULT '1',
    MODIFY COLUMN `isemrino` VARCHAR(255) NULL DEFAULT '',
    MODIFY COLUMN `last_control_date` VARCHAR(20) NULL DEFAULT '',
    MODIFY COLUMN `control_date` VARCHAR(30) NULL DEFAULT '',
    MODIFY COLUMN `next_control_date` VARCHAR(20) NULL DEFAULT '',
    MODIFY COLUMN `control_period` VARCHAR(30) NULL DEFAULT '',
    MODIFY COLUMN `validity_date` VARCHAR(30) NULL DEFAULT '',
    MODIFY COLUMN `customer_id` INT(11) NULL DEFAULT 0,
    MODIFY COLUMN `standarts` TEXT NULL DEFAULT NULL,
    MODIFY COLUMN `equipments` TEXT NULL DEFAULT NULL,
    MODIFY COLUMN `warnings` TEXT NULL DEFAULT NULL,
    MODIFY COLUMN `notes` TEXT NULL DEFAULT NULL,
    MODIFY COLUMN `subNotes` TEXT NULL DEFAULT NULL,
    MODIFY COLUMN `controller_id` INT(100) NULL DEFAULT 0,
    MODIFY COLUMN `company_official` INT(100) NULL DEFAULT 0,
    MODIFY COLUMN `test_date` VARCHAR(20) NULL DEFAULT '',
    MODIFY COLUMN `servis_no` VARCHAR(50) NULL DEFAULT '',
    MODIFY COLUMN `report_matters` LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN `bakim_bilgileri` LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN `dedektor_info` LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN `oys_general_matters` LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN `controller_peak_info` LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN `creator` INT(10) NULL DEFAULT 0,
    MODIFY COLUMN `create_time` VARCHAR(20) NULL DEFAULT NULL,
    MODIFY COLUMN `updater` INT(20) NULL DEFAULT 0,
    MODIFY COLUMN `update_time` VARCHAR(20) NULL DEFAULT '';

ALTER TABLE `report_hst_content`
    MODIFY COLUMN `testno` VARCHAR(100) NULL DEFAULT '',
    MODIFY COLUMN `kg` VARCHAR(100) NULL DEFAULT '',
    MODIFY COLUMN `cinsi` VARCHAR(100) NULL DEFAULT '',
    MODIFY COLUMN `imalatci_firma` VARCHAR(100) NULL DEFAULT '',
    MODIFY COLUMN `imal_tarihi` VARCHAR(20) NULL DEFAULT '',
    MODIFY COLUMN `serino` VARCHAR(100) NULL DEFAULT '',
    MODIFY COLUMN `tse_belgesi` VARCHAR(1) NULL DEFAULT '1',
    MODIFY COLUMN `yuzey_durumu` VARCHAR(1) NULL DEFAULT '1',
    MODIFY COLUMN `sizdirmazlik_deneyi` VARCHAR(1) NULL DEFAULT '1',
    MODIFY COLUMN `esneme_deneyi` VARCHAR(1) NULL DEFAULT '1',
    MODIFY COLUMN `things` VARCHAR(1000) NULL DEFAULT '';
